/**
 * Report Export - Generate and download analysis reports
 * PDF/Print-ready export with executive summary
 */
import React, { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import {
  Download, FileText, Printer, Copy, CheckCircle2,
  Clock, Shield, AlertTriangle, Target
} from 'lucide-react';
import type { Timeline, OrchestrationResponse } from '../../types/incident';

interface ReportExportProps {
  timeline: Timeline;
  orchestrationResult?: OrchestrationResponse | null;
  incidentId?: string;
  analysisTime?: number;
  remediationPlan?: any;
}

const ReportExport: React.FC<ReportExportProps> = ({
  timeline,
  orchestrationResult,
  incidentId,
  analysisTime,
  remediationPlan,
}) => {
  const [copied, setCopied] = useState(false);
  

  const generateReport = useCallback(() => {
    const events = timeline?.events || [];
    const criticalCount = events.filter(e => (e.severity as string)?.toUpperCase() === 'CRITICAL').length;
    const highCount = events.filter(e => (e.severity as string)?.toUpperCase() === 'HIGH').length;
    const mediumCount = events.filter(e => (e.severity as string)?.toUpperCase() === 'MEDIUM').length;
    const lowCount = events.filter(e => (e.severity as string)?.toUpperCase() === 'LOW').length;
    const confidence = timeline?.confidence || 0;

    const steps = remediationPlan?.steps || [];

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    return `
════════════════════════════════════════════════════════════════
  NOVA SENTINEL — SECURITY INCIDENT REPORT
  Generated: ${dateStr} at ${timeStr}
════════════════════════════════════════════════════════════════

INCIDENT ID:     ${incidentId || 'N/A'}
ANALYSIS TIME:   ${analysisTime ? `${(analysisTime / 1000).toFixed(1)} seconds` : 'N/A'}
AI CONFIDENCE:   ${(confidence * 100).toFixed(0)}%
MODEL PIPELINE:  Nova Pro → Nova 2 Lite → Nova Micro → Orchestrator → Nova 2 Lite

────────────────────────────────────────────────────────────────
  EXECUTIVE SUMMARY
────────────────────────────────────────────────────────────────

Root Cause:
  ${timeline?.root_cause || 'Not determined'}

Attack Pattern:
  ${timeline?.attack_pattern || 'Not determined'}

Blast Radius:
  ${timeline?.blast_radius || 'Not determined'}

────────────────────────────────────────────────────────────────
  RISK DISTRIBUTION
────────────────────────────────────────────────────────────────

  Total Events:  ${events.length}
  Critical:      ${criticalCount} ${'█'.repeat(criticalCount)} 
  High:          ${highCount} ${'█'.repeat(highCount)}
  Medium:        ${mediumCount} ${'█'.repeat(mediumCount)}
  Low:           ${lowCount} ${'█'.repeat(lowCount)}

────────────────────────────────────────────────────────────────
  EVENT TIMELINE
────────────────────────────────────────────────────────────────

${events.map((e: any, i: number) => `  [${String(i + 1).padStart(2, '0')}] ${e.severity?.toUpperCase()?.padEnd(8) || 'UNKNOWN '} | ${e.event_name || e.action || 'Unknown Event'}
       ${e.description || ''}
       Actor: ${e.actor || 'Unknown'}  Resource: ${e.resource || 'Unknown'}
       Time: ${e.timestamp || 'N/A'}
`).join('\n')}

────────────────────────────────────────────────────────────────
  REMEDIATION PLAN
────────────────────────────────────────────────────────────────

${steps.length > 0 ? steps.map((s: any, i: number) => `  Step ${i + 1}: [${s.priority?.toUpperCase() || 'MEDIUM'}] ${s.action || s.title || 'Unknown'}
    ${s.details || s.description || ''}
`).join('\n') : '  No remediation plan generated yet.'}

────────────────────────────────────────────────────────────────
  COMPLIANCE IMPACT
────────────────────────────────────────────────────────────────

  Frameworks Assessed: CIS Benchmarks, NIST 800-53, SOC 2, PCI-DSS
  Status: See Compliance Mapping feature for detailed control mappings

────────────────────────────────────────────────────────────────
  COST IMPACT ESTIMATE
────────────────────────────────────────────────────────────────

  See Cost Impact Estimation feature for detailed financial analysis
  including breach liability, downtime costs, and ROI calculation.

════════════════════════════════════════════════════════════════
  Report generated by Nova Sentinel
  Built with Amazon Nova AI for the Amazon Nova AI Hackathon 2026
  
  Models: Nova Pro, Nova 2 Lite, Nova Micro, Nova 2 Sonic, Nova Act
  Infrastructure: MCP Server, Strands Agents Framework
════════════════════════════════════════════════════════════════
`.trim();
  }, [timeline, orchestrationResult, incidentId, analysisTime, remediationPlan]);

  const handleCopyReport = async () => {
    const report = generateReport();
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textArea = document.createElement('textarea');
      textArea.value = report;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadReport = () => {
    const report = generateReport();
    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `nova-sentinel-report-${incidentId || 'analysis'}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrintReport = () => {
    const report = generateReport();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Nova Sentinel - Incident Report ${incidentId || ''}</title>
            <style>
              body { font-family: 'Courier New', monospace; font-size: 12px; padding: 40px; line-height: 1.6; color: #1e293b; }
              pre { white-space: pre-wrap; word-wrap: break-word; }
              @media print { body { padding: 20px; } }
            </style>
          </head>
          <body><pre>${report}</pre></body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="space-y-5">
      {/* Export Options */}
      <div className="bg-white rounded-xl border border-slate-200 p-6">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center">
            <FileText className="w-5 h-5 text-white" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900">Export Analysis Report</h3>
            <p className="text-xs text-slate-500">Generate a comprehensive incident report for your team</p>
          </div>
        </div>

        <div className="grid sm:grid-cols-3 gap-4 mb-6">
          {/* Download TXT */}
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleDownloadReport}
            className="flex flex-col items-center gap-3 p-5 bg-slate-50 hover:bg-indigo-50 border border-slate-200 hover:border-indigo-300 rounded-xl transition-all group"
          >
            <div className="w-12 h-12 rounded-xl bg-white border border-slate-200 group-hover:border-indigo-300 flex items-center justify-center transition-colors">
              <Download className="w-5 h-5 text-slate-600 group-hover:text-indigo-600 transition-colors" />
            </div>
            <div className="text-center">
              <p className="text-sm font-bold text-slate-900 group-hover:text-indigo-600 transition-colors">Download Report</p>
              <p className="text-[10px] text-slate-400">Save as .txt file</p>
            </div>
          </motion.button>

          {/* Copy to Clipboard */}
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleCopyReport}
            className="flex flex-col items-center gap-3 p-5 bg-slate-50 hover:bg-emerald-50 border border-slate-200 hover:border-emerald-300 rounded-xl transition-all group"
          >
            <div className="w-12 h-12 rounded-xl bg-white border border-slate-200 group-hover:border-emerald-300 flex items-center justify-center transition-colors">
              {copied ? (
                <CheckCircle2 className="w-5 h-5 text-emerald-600" />
              ) : (
                <Copy className="w-5 h-5 text-slate-600 group-hover:text-emerald-600 transition-colors" />
              )}
            </div>
            <div className="text-center">
              <p className="text-sm font-bold text-slate-900 group-hover:text-emerald-600 transition-colors">
                {copied ? 'Copied!' : 'Copy to Clipboard'}
              </p>
              <p className="text-[10px] text-slate-400">Paste into Slack, JIRA, etc.</p>
            </div>
          </motion.button>

          {/* Print / PDF */}
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handlePrintReport}
            className="flex flex-col items-center gap-3 p-5 bg-slate-50 hover:bg-violet-50 border border-slate-200 hover:border-violet-300 rounded-xl transition-all group"
          >
            <div className="w-12 h-12 rounded-xl bg-white border border-slate-200 group-hover:border-violet-300 flex items-center justify-center transition-colors">
              <Printer className="w-5 h-5 text-slate-600 group-hover:text-violet-600 transition-colors" />
            </div>
            <div className="text-center">
              <p className="text-sm font-bold text-slate-900 group-hover:text-violet-600 transition-colors">Print / Save PDF</p>
              <p className="text-[10px] text-slate-400">Use browser Save as PDF</p>
            </div>
          </motion.button>
        </div>

        {/* Report Preview */}
        <div className="bg-slate-900 rounded-xl p-5 overflow-hidden">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-red-500" />
              <div className="w-3 h-3 rounded-full bg-amber-500" />
              <div className="w-3 h-3 rounded-full bg-emerald-500" />
            </div>
            <span className="text-[10px] text-slate-500 font-mono">nova-sentinel-report.txt</span>
          </div>
          <pre className="text-[10px] text-slate-400 font-mono leading-relaxed overflow-x-auto max-h-60 scrollbar-thin">
{`NOVA SENTINEL — SECURITY INCIDENT REPORT

INCIDENT ID:   ${incidentId || 'N/A'}
ANALYSIS TIME: ${analysisTime ? `${(analysisTime / 1000).toFixed(1)}s` : 'N/A'}
CONFIDENCE:    ${((timeline?.confidence || 0) * 100).toFixed(0)}%

ROOT CAUSE:    ${(timeline?.root_cause || 'Not determined').slice(0, 80)}...
ATTACK:        ${(timeline?.attack_pattern || 'Not determined').slice(0, 80)}...
EVENTS:        ${timeline?.events?.length || 0} total

[Download full report for complete details]`}
          </pre>
        </div>
      </div>

      {/* Report Contents Summary */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <h4 className="text-sm font-bold text-slate-900 mb-3">Report Includes</h4>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { label: 'Executive Summary', icon: FileText, check: true },
            { label: 'Risk Distribution', icon: AlertTriangle, check: true },
            { label: 'Event Timeline', icon: Clock, check: true },
            { label: 'Remediation Plan', icon: Shield, check: !!remediationPlan },
            { label: 'Compliance Impact', icon: Target, check: true },
            { label: 'Cost Estimation', icon: Target, check: true },
            { label: 'Attack Pattern', icon: Target, check: true },
            { label: 'Blast Radius', icon: Target, check: true },
          ].map((item) => (
            <div key={item.label} className="flex items-center gap-2 p-2 rounded-lg bg-slate-50">
              <CheckCircle2 className={`w-3.5 h-3.5 ${item.check ? 'text-emerald-500' : 'text-slate-300'}`} />
              <span className={`text-[11px] font-medium ${item.check ? 'text-slate-700' : 'text-slate-400'}`}>
                {item.label}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ReportExport;
