"""
Remediation API endpoints — plan generation, execution, approval
"""
import asyncio
from fastapi import APIRouter, HTTPException, Query
from typing import Dict, Any, Optional
from dataclasses import asdict
from datetime import datetime

from agents.remediation_agent import RemediationAgent
from services.remediation_executor import RemediationExecutor, ExecutionResult
from services.approval_manager import (
    create_pending_approval,
    get_pending,
    approve_and_get,
    list_pending,
    store_execution_proof,
    get_execution_proofs,
)
from utils.logger import logger

router = APIRouter(prefix="/api/remediation", tags=["remediation"])
remediation_agent = RemediationAgent()


@router.post("/generate-plan")
async def generate_plan(
    incident_analysis: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Generate a remediation plan for a security incident
    
    Args:
        incident_analysis: Full incident analysis with timeline, root cause, etc.
        
    Returns:
        Remediation plan with steps and validation
    """
    try:
        logger.info("Received remediation plan generation request")
        
        # Extract required fields
        timeline = incident_analysis.get("timeline", {})
        root_cause = timeline.get("root_cause", "Unknown")
        attack_pattern = timeline.get("attack_pattern", "Unknown")
        blast_radius = timeline.get("blast_radius", "Unknown")
        events = timeline.get("events", [])
        
        # Generate plan
        plan = await remediation_agent.generate_remediation_plan(
            incident_analysis=incident_analysis,
            root_cause=root_cause,
            attack_pattern=attack_pattern,
            blast_radius=blast_radius,
            timeline_events=events
        )
        
        return plan
        
    except Exception as e:
        import traceback
        logger.error(f"Error generating remediation plan: {e}\n{traceback.format_exc()}")
        raise HTTPException(
            status_code=500,
            detail=f"Remediation plan generation failed: {str(e)}"
        )


@router.post("/validate-plan")
async def validate_plan(
    plan: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Validate a remediation plan for safety and compliance
    
    Args:
        plan: Remediation plan to validate
        
    Returns:
        Validation results
    """
    try:
        logger.info(f"Validating remediation plan: {plan.get('plan_id', 'Unknown')}")
        
        validation = await remediation_agent.validate_plan(plan)
        
        return validation
        
    except Exception as e:
        import traceback
        logger.error(f"Error validating plan: {e}\n{traceback.format_exc()}")
        raise HTTPException(
            status_code=500,
            detail=f"Plan validation failed: {str(e)}"
        )


@router.post("/execute/{step_id}")
async def execute_step(
    step_id: str,
    incident_id: str = Query(...),
    action: str = Query(...),
    target: str = Query(...),
    demo_mode: bool = Query(False),
    # Optional enrichment — pass from frontend when available
    policy_arn: Optional[str] = Query(None),
    instance_ids: Optional[str] = Query(None),  # comma-separated
    sg_id: Optional[str] = Query(None),
    port: Optional[int] = Query(None),
    cidr: Optional[str] = Query(None),
    username: Optional[str] = Query(None),
) -> Dict[str, Any]:
    """
    Execute a specific remediation step using the real AWS API (or simulate in demo_mode).

    Routing logic: matches the natural-language `action` description generated by the
    RemediationAgent to the correct executor method.
    """
    try:
        executor = RemediationExecutor(demo_mode=demo_mode)
        a = (action or "").lower()
        t = (target or "unknown").strip()
        result: Optional[ExecutionResult] = None

        # ── Revoke active role sessions (must come before generic "policy" match) ──
        if "revoke" in a and ("session" in a or "role" in a):
            role = _extract_role_name(t, a)
            result = await executor.execute_revoke_role_sessions(role, incident_id)

        # ── Detach managed policy (AdministratorAccess etc.) ──
        elif ("detach" in a and "policy" in a) or ("administratoraccess" in a) or ("detach" in a and "admin" in a):
            role = _extract_role_name(t, a)
            parn = (
                policy_arn
                or _extract_policy_arn(a)
                or "arn:aws:iam::aws:policy/AdministratorAccess"
            )
            result = await executor.execute_detach_managed_policy(role, parn, incident_id)

        # ── Terminate EC2 instances ──
        elif "terminate" in a and ("instance" in a or "ec2" in a):
            ids = []
            if instance_ids:
                ids = [i.strip() for i in instance_ids.split(",") if i.strip()]
            if not ids:
                ids = _extract_instance_ids(t, a)
            if not ids:
                # Cannot determine real instance IDs — return guidance instead of calling EC2 with a fake ID
                result = ExecutionResult(
                    action_type="TERMINATE_INSTANCES",
                    status="MANUAL_REQUIRED",
                    resource_arn="arn:aws:ec2:::instance/*",
                    before_state={}, after_state={},
                    rollback_command="",
                    cloudtrail_event={},
                    execution_timestamp=datetime.utcnow().isoformat() + "Z",
                    executed_by="MANUAL",
                    incident_id=incident_id,
                    message=(
                        "Could not determine instance IDs from the step description. "
                        "Run: aws ec2 describe-instances --filters 'Name=tag:WOLFIR-QUARANTINE,Values=true' "
                        "to find quarantined instances, then: aws ec2 terminate-instances --instance-ids <id1> <id2>"
                    ),
                )
            else:
                result = await executor.execute_terminate_instances(ids, incident_id)

        # ── Revoke / restore security group rules ──
        elif ("revoke" in a or "restore" in a or "security group" in a) and ("sg" in a.replace("-", "") or "port" in a or "ssh" in a or "ingress" in a):
            gid = sg_id or _extract_sg_id(t, a) or t
            p = port or (22 if "ssh" in a else 0)
            c = cidr or "0.0.0.0/0"
            result = await executor.execute_revoke_security_group_ingress(gid, p, c, "tcp", incident_id)

        # ── Disable access key ──
        elif "disable" in a and "key" in a:
            user = username or _extract_username(t, a) or t
            result = await executor.execute_disable_access_key("AKIAEXAMPLE", user, incident_id)

        # ── Quarantine tag ──
        elif "tag" in a or "quarantine" in a:
            # IAM ARNs require account ID — arn:aws:iam::<account>:role/<name>
            if t.startswith("arn:"):
                arn = t
            else:
                role = _extract_role_name(t, a)
                # Fetch real account ID via STS; fall back to placeholder if unavailable
                try:
                    import boto3 as _boto3
                    account_id = _boto3.client("sts").get_caller_identity()["Account"]
                except Exception:
                    account_id = "UNKNOWN"
                arn = f"arn:aws:iam::{account_id}:role/{role}"
            result = await executor.execute_quarantine_tag(arn, incident_id)

        # ── Attach emergency deny policy (generic containment) ──
        elif "deny" in a or ("attach" in a and "policy" in a):
            role = _extract_role_name(t, a)
            result = await executor.execute_deny_policy(role, ["*"], incident_id)

        # ── Enable MFA — cannot be automated, return guidance ──
        elif "mfa" in a or "multi-factor" in a:
            user = username or _extract_username(t, a) or t
            result = ExecutionResult(
                action_type="MFA_ENABLEMENT",
                status="MANUAL_REQUIRED",
                resource_arn=f"arn:aws:iam::unknown:user/{user}",
                before_state={},
                after_state={},
                rollback_command="",
                cloudtrail_event={},
                execution_timestamp=datetime.utcnow().isoformat() + "Z",
                executed_by="MANUAL",
                incident_id=incident_id,
                message=(
                    "MFA enrollment cannot be fully automated — it requires the user to scan a QR code. "
                    "Use: aws iam create-virtual-mfa-device --virtual-mfa-device-name <name> "
                    "then aws iam enable-mfa-device --user-name <user> --serial-number <arn> "
                    "--authentication-code1 <code1> --authentication-code2 <code2>"
                ),
            )

        # ── Default: generic deny-all containment ──
        else:
            role = _extract_role_name(t, a)
            result = await executor.execute_deny_policy(role, ["*"], incident_id)

        proof = asdict(result)
        store_execution_proof(incident_id, proof)
        return {"status": result.status.lower(), "execution_proof": proof}

    except Exception as e:
        import traceback
        logger.error(f"Execute step failed: {e}\n{traceback.format_exc()}")
        raise HTTPException(status_code=500, detail=str(e))


# ── Helper extractors ────────────────────────────────────────────────────────

def _extract_role_name(target: str, action: str) -> str:
    """Pull a role name from target string or action text."""
    import re
    for text in [target, action]:
        m = re.search(r"(?:role[:/\s-]+)([\w-]+)", text, re.I)
        if m:
            return m.group(1)
        m = re.search(r"([\w-]+role[\w-]*)", text, re.I)
        if m:
            return m.group(1)
    return target or "unknown-role"


def _extract_policy_arn(action: str) -> Optional[str]:
    """Extract a policy ARN from action text."""
    import re
    m = re.search(r"(arn:aws:iam::[^'\s]+)", action)
    if m:
        return m.group(1)
    if "administratoraccess" in action.lower():
        return "arn:aws:iam::aws:policy/AdministratorAccess"
    if "readonlyaccess" in action.lower():
        return "arn:aws:iam::aws:policy/ReadOnlyAccess"
    return None


def _extract_instance_ids(target: str, action: str) -> list:
    import re
    ids = re.findall(r"i-[0-9a-f]{8,17}", target + " " + action, re.I)
    return list(set(ids))


def _extract_sg_id(target: str, action: str) -> Optional[str]:
    import re
    m = re.search(r"sg-[0-9a-f]{6,17}", target + " " + action, re.I)
    return m.group(0) if m else None


def _extract_username(target: str, action: str) -> Optional[str]:
    import re
    for text in [target, action]:
        m = re.search(r"user[:/\s-]+([\w-]+)", text, re.I)
        if m:
            return m.group(1)
    return None


@router.post("/approve/{approval_token}")
async def approve_remediation(approval_token: str) -> Dict[str, Any]:
    """Approve a pending remediation and execute."""
    p = approve_and_get(approval_token)
    if not p:
        raise HTTPException(status_code=404, detail="Approval not found or already processed")
    # Use demo_mode from approval if stored; default False for real execution
    demo_mode = p.get("demo_mode", False)
    exec = RemediationExecutor(demo_mode=demo_mode)
    # Pass empty string for key_id so executor auto-discovers via iam.list_access_keys
    result = await exec.execute_disable_access_key(
        p["params"].get("access_key_id", ""),
        p.get("target", "unknown"),
        p.get("incident_id", "INC-DEMO"),
    )
    store_execution_proof(p["incident_id"], asdict(result))
    return {"status": "approved", "execution_proof": asdict(result)}


@router.get("/execution-proof/{incident_id}")
async def get_execution_proof(incident_id: str) -> Dict[str, Any]:
    """Get all execution proofs for an incident."""
    proofs = get_execution_proofs(incident_id)
    return {"incident_id": incident_id, "proofs": proofs, "count": len(proofs)}


@router.get("/pending-approvals")
async def get_pending_approvals(incident_id: Optional[str] = Query(None)) -> Dict[str, Any]:
    """List all pending human approvals."""
    items = list_pending(incident_id)
    return {"pending": items, "count": len(items)}


@router.get("/health")
async def health_check() -> Dict[str, str]:
    """Health check endpoint"""
    return {
        "status": "healthy",
        "service": "remediation-api",
        "model": "amazon.nova-lite-v1:0",
    }
